# Generated by Django 6.0.3 on 2026-03-18 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("Happy", "Happy"),
                            ("Sad", "Sad"),
                            ("Energetic", "Energetic"),
                            ("Calm", "Calm"),
                            ("Angry", "Angry"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "occasion",
                    models.CharField(
                        choices=[
                            ("Wedding", "Wedding"),
                            ("Party", "Party"),
                            ("Workout", "Workout"),
                            ("Study", "Study"),
                            ("Relaxation", "Relaxation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop", "Pop"),
                            ("Rock", "Rock"),
                            ("Jazz", "Jazz"),
                            ("Classical", "Classical"),
                            ("Electronic", "Electronic"),
                            ("Hip-Hop", "Hip-Hop"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "singer_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Non-binary", "Non-binary"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Generating", "Generating"),
                            ("Ready", "Ready"),
                            ("Failed", "Failed"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("audio_url", models.URLField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="core.playlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
