# Generated by Django 6.0.3 on 2026-03-18 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="audio_format",
            field=models.CharField(
                choices=[("MP3", "MP3"), ("M4A", "M4A")], default="MP3", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="reference_url",
            field=models.URLField(
                blank=True, help_text="Optional reference song URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="share_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="core.playlist",
            ),
        ),
    ]
