# Generated by Django 6.0.3 on 2026-03-18 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_song_audio_format_song_reference_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="share_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
