# Generated by Django 6.0.3 on 2026-04-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_song_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="suno_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
