# Generated by Django 6.0.3 on 2026-04-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_song_suno_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="playlist",
        ),
        migrations.AddField(
            model_name="song",
            name="playlists",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="core.playlist"
            ),
        ),
    ]
